### PR TITLE
Update bindings for 0.25.1

### PR DESCRIPTION
**Pull request by Weyzu**
Following up from PR: s-ludwig/dlibgit/pull/9

These are the updates for larger support of `libgit2` 0.25.1 that I managed to finish, up until now. There is still work to be done, as I am more or less 33% done (counting by modules to do, not actual lines of code).

I made one commit per one module. Commits have descriptive messages so that changes and additions can be searched from within the git log. IMO, it helps in checking when, if and where a binding was added.

### CODE REVIEW

**Comment by s-ludwig** [comment]
Thanks! Going to merge this as-is for now. I'll try to follow up with own additions or fixes when I get the time to actually test this.

**Comment by s-ludwig** [comment]
Looks like there are still some omissions: https://travis-ci.org/s-ludwig/libgit2/builds/245371797

**Comment by Weyzu** [comment]
Ah, sorry. I'll post fixes to those issues in a couple of hours. 

Also, the build seems to be downloading v0.20.0 of libgit2.

**Comment by s-ludwig** [comment]
Okay, great. I've pushed a fix for the libgit version: https://travis-ci.org/s-ludwig/libgit2/builds/245374195

**Pull request merged**
